kind: cmake

build-depends:
- freedesktop-sdk.bst:public-stacks/buildsystem-cmake.bst
- components/kf6/extra-cmake-modules.bst

depends:
- freedesktop-sdk.bst:public-stacks/runtime-minimal.bst
- components/qt6/qtbase.bst
- components/qt6/qtdeclarative.bst
- components/qt6/qttools.bst
- components/kf6/kcmutils.bst
- components/kf6/kcolorscheme.bst
- components/kf6/kconfig.bst
- components/kf6/kcoreaddons.bst
- components/kf6/ki18n.bst
- components/kf6/kirigami.bst
- components/kf6/knewstuff.bst
- components/kf6/kpackage.bst
- components/kf6/ksvg.bst
- components/plasma/kdecoration.bst

variables:
  cmake-local: |
    -DBUILD_TESTING=OFF \

sources:
- kind: tar
  url: 'kde_stable:plasma/%{plasma-version}/aurorae-%{plasma-version}.tar.xz'
  ref: a8d01edd3f046ed41b32d4f10d23f7be2d05e69b836f5b358e994b2405c73092
