kind: cmake

build-depends:
- freedesktop-sdk.bst:public-stacks/buildsystem-cmake.bst
- components/kf6/extra-cmake-modules.bst

depends:
- freedesktop-sdk.bst:public-stacks/runtime-minimal.bst
- components/qt6/qtbase.bst
- components/qt6/qtdeclarative.bst
- components/qt6/qtsvg.bst
- components/kf6/kauth.bst
- components/kf6/kcoreaddons.bst
- components/kf6/kconfig.bst
- components/kf6/ki18n.bst
- components/kf6/kpackage.bst
- components/plasma/libkscreen.bst
- components/plasma/plasma-desktop.bst
- components/plasma/plasma-workspace.bst

variables:
  cmake-local: |
    -DBUILD_TESTING=OFF \
    -DCMAKE_BUILD_TYPE=Release

sources:
- kind: git_repo
  url: 'kde:plasma/plasma-setup.git'
  track: master
  ref: be8701ec4417d0de30343f62b114a4ae2db18f63
- kind: patch_queue
  path: patches/plasma-setup
