kind: stack

depends:
- components/gear/konsole.bst
- components/gear/kwrite.bst
- components/gear/dolphin.bst
- components/gear/ark.bst
- components/gear/partitionmanager.bst
- components/gear/audiocd-kio.bst
- components/gear/filelight.bst
- components/gear/kcharselect.bst
- components/gear/kdeconnect-kde.bst
- components/gear/kfind.bst
- components/gear/kio-admin.bst
#- components/gear/khelpcenter.bst # wait for Qt6WebEngine
