kind: stack

depends:
  - components/plasma/kdecoration.bst
  - components/plasma/libkscreen.bst
  - components/plasma/libksysguard.bst
  - components/plasma/breeze.bst
  - components/plasma/breeze-gtk.bst
  - components/plasma/layer-shell-qt.bst
  - components/plasma/plasma-activities.bst
  - components/plasma/libplasma.bst
  - components/plasma/kscreenlocker.bst
  - components/plasma/kinfocenter.bst
  - components/plasma/kwayland.bst
  - components/plasma/aurorae.bst
  - components/plasma/knighttime.bst
  - components/plasma/kwin.bst
  - components/plasma/plasma5support.bst
  - components/plasma/kpipewire.bst
  - components/plasma/plasma-workspace.bst
  - components/plasma/plasma-disks.bst
  - components/plasma/bluedevil.bst
  - components/plasma/kde-gtk-config.bst
  - components/plasma/kmenuedit.bst
  - components/plasma/kscreen.bst
  - components/plasma/kwallet-pam.bst
  - components/plasma/kwrited.bst
  - components/plasma/milou.bst
  - components/plasma/plasma-nm.bst
  - components/plasma/plasma-pa.bst
  - components/plasma/plasma-workspace-wallpapers.bst
  - components/plasma/polkit-kde-agent.bst
  - components/plasma/powerdevil.bst
  - components/plasma/plasma-desktop.bst
  - components/plasma/ksshaskpass.bst
  - components/plasma/discover.bst
  - components/plasma/kactivitymanagerd.bst
  - components/plasma/plasma-integration.bst
  - components/plasma/xdg-desktop-portal-kde.bst
  - components/plasma/drkonqi.bst
  - components/plasma/plasma-vault.bst
  - components/plasma/kde-cli-tools.bst
  - components/plasma/systemsettings.bst
  - components/plasma/plasma-thunderbolt.bst
  - components/plasma/plasma-firewall.bst
  - components/plasma/plasma-systemmonitor.bst
  # - components/plasma/qqc2-breeze-style.bst
  - components/plasma/ksystemstats.bst
  - components/plasma/kdeplasma-addons.bst
  - components/plasma/flatpak-kcm.bst
  - components/plasma/plasma-welcome.bst
  - components/plasma/ocean-sound-theme.bst
  # - components/plasma/print-manager.bst
  # - components/plasma/krdp.bst
  - components/plasma/spectacle.bst
  # Experimental things
  - components/plasma/plasma-login-manager.bst
  - components/plasma/plasma-setup.bst
  # obsolete things
  # - components/plasma/wacomtablet.bst
  # - components/plasma/oxygen.bst
  #- components/plasma/oxygen-sounds.bst
  #- components/plasma/kgamma.bst
  # - components/plasma/sddm-kcm.bst
